### ISSUE TITLE
Nice meme mod

### ISSUE THREAD

**Issue by ipoopedmypantsuups** [EIA485/NeosYouWantDarkmode#1]
Not sure if this is a joke or not but this makes the menus unusable

![image](https://steamuserimages-a.akamaihd.net/ugc/1861690611958279137/5B797A373CB2CD2B1F6DACCB521272729AE13C48/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)
![image](https://steamuserimages-a.akamaihd.net/ugc/1861690611958279231/619E4EDAC1615C60FC72A0CC3A3F46CC14E91D22/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)
![image](https://steamuserimages-a.akamaihd.net/ugc/1861690611958279302/2C411E96E123D3B2A74BD5421CB7587ADA847FBA/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

**Comment by EIA485** [comment]
yep, thats what this mod does.
